# Generated by Django 3.2.20 on 2023-07-28 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20230728_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='document',
            field=models.FileField(upload_to='newsletters/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
    ]
