# Generated by Django 3.2.20 on 2023-07-28 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_alter_newsletter_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='newsletter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter.newsletter'),
        ),
    ]
