# Generated by Django 3.2.20 on 2023-07-28 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_auto_20230728_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='is_subscribed',
        ),
    ]
