# Generated by Django 3.2.20 on 2023-07-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_auto_20230728_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='subscribed_newsletters',
            field=models.ManyToManyField(blank=True, to='newsletter.CategoryNewsletter'),
        ),
    ]
