# Generated by Django 3.2.20 on 2023-08-01 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_alter_subscriber_subscribed_newsletters'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.newsletter')),
                ('subscribers', models.ManyToManyField(to='newsletter.Subscriber')),
            ],
        ),
    ]
