# Generated by Django 3.2.20 on 2023-08-01 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0010_schedulednewsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulednewsletter',
            name='newsletter',
        ),
        migrations.AddField(
            model_name='schedulednewsletter',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='newsletter.categorynewsletter'),
            preserve_default=False,
        ),
    ]
