# Generated by Django 3.2.20 on 2023-08-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0011_auto_20230801_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulednewsletter',
            name='subscribers',
        ),
    ]
